// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBScGqs6qEKQBc1Sc4xMKKLxZStYXPK-dI',
    appId: '1:707246097288:web:922f54d3faf2dd63ee703d',
    messagingSenderId: '707246097288',
    projectId: 'app-teste-viacredi',
    authDomain: 'app-teste-viacredi.firebaseapp.com',
    storageBucket: 'app-teste-viacredi.firebasestorage.app',
    measurementId: 'G-D8G63EVKMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfB1HAonXkUvZ0KF1XO1HlVWfV7rGgiaQ',
    appId: '1:707246097288:android:0b6e192bd53d680eee703d',
    messagingSenderId: '707246097288',
    projectId: 'app-teste-viacredi',
    storageBucket: 'app-teste-viacredi.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBScGqs6qEKQBc1Sc4xMKKLxZStYXPK-dI',
    appId: '1:707246097288:web:93f6bdd97d1c96f7ee703d',
    messagingSenderId: '707246097288',
    projectId: 'app-teste-viacredi',
    authDomain: 'app-teste-viacredi.firebaseapp.com',
    storageBucket: 'app-teste-viacredi.firebasestorage.app',
    measurementId: 'G-FKX7GGRWB4',
  );
}
